### ISSUE TITLE
How best to contribute?

### ISSUE THREAD

**Issue by sheldon** [boolder-org/boolder-data#2]
Hey there Nicolas & team

Firstly, thanks so much for your efforts on boolder. I just used it first time yesterday at Saint Germain and it's really great.

I took a bunch of photos of climbs that aren't included, and I'd like to add them to the data repo. It's incomplete data, a few of the white circuit and 1 missing yellow. Should I start to prepare the data to be added in a pull request? Any other advice about contributing, e.g. do you only accept adding circuits if the majority of the routes are included?

Also, I have a software engineering background, and might consider contributing on the apps or website too. I saw the repos for the apps are available but not the website. Web is my core area, so I'm wondering if you plan to open source the web app? If not, what's interesting to work on for the mobile apps?

Cheers
Sheldon

**Comment by ZodiacFRA** [comment]
Hey, One of the areas I go (Buthiers) is missing sectors (Buthiers canard, nord & tennis).
Is it worth it to add those and submit a PR? Dou you accept data PRs?

Merci pour votre taf :)

**Comment by nmondollot** [comment]
Hello!
Thanks for contributing, that's great!

The `boolder-data` repo is read-only for now.
Adding new data (eg. problems, circuits) requires going through the core database and web interface (not open sourced yet).
I'm working on a new page to allow anyone to propose updates and new data. I will let you know as soon as it's ready.

In the meantime, can you send me your photos and data at hello@boolder.com? It's ok if it's incomplete.

> Any other advice about contributing, e.g. do you only accept adding circuits if the majority of the routes are included?

For big updates (like whole new circuits) it's best to discuss it with me directly via email.
FYI we don't list kids circuit for now (but we will eventually).

> Also, I have a software engineering background, and might consider contributing on the apps or website too. I saw the repos for the apps are available but not the website. Web is my core area, so I'm wondering if you plan to open source the web app? If not, what's interesting to work on for the mobile apps?

Great!!
I will probably open-source the website in the coming months, but no clear ETA for now. FYI it's written in Ruby on Rails.
If you're really interested in contributing to the website before it's open sourced, let's have a chat about it!

Regarding the mobile apps: the priority is clearly to get the Android app up to speed with the iPhone app.
A lot of features are currently missing from the Android app, like seeing the list of areas, tick problems, use filters on the map, ...
On iPhone I will soon start working on the offline mode, which is also a pretty interesting problem :)

**Comment by nmondollot** [comment]
> Hey, One of the areas I go (Buthiers) is missing sectors (Buthiers canard, nord & tennis). Is it worth it to add those and submit a PR? Dou you accept data PRs?

Buthiers Canard and Tennis are on our todo list for the coming weeks.
New areas require a lot of work (~1 day per area, taking photos and GPS coordinates with a custom-built app).
We are currently 2 people in the core mapping team.
Do you want to join us? Please drop us a line at hello@boolder.com !

> Merci pour votre taf :)

🙏 ❤️

**Comment by sheldon** [comment]
Thanks for the details, I'll reach out on email and share the photos :)
