### ISSUE TITLE
Wrong start

### ISSUE THREAD

**Issue by pkamps** [boolder-org/boolder-data#4]
https://www.boolder.com/en/fontainebleau/roche-aux-oiseaux/6354-anti-dogme

it starts higher up - it's not the sitstart variation (anti-dogme-assi).

**Comment by nmondollot** [comment]
Thanks for the feedback!
I will add the sit start version.

**Comment by nmondollot** [comment]
Hey!

I added the sit start version:
https://www.boolder.com/en/fontainebleau/roche-aux-oiseaux/22622-anti-dogme-assis

Thanks for your feedback.

And FYI we'll soon launch a new page to report errors and contribute to Boolder
Preview here: https://www.boolder.com/en/contribute
