### ISSUE TITLE
Bloc mal renseigné au mont Ussy.

### ISSUE THREAD

**Issue by miggazElquez** [boolder-org/boolder-data#5]
Bonjour.

Certains blocs au mont Ussy dans les circuits faciles sont mal renseignés : 

Par exemple, le n°2 du circuit jaune (bien placé sur la carte et bien tracé sur l'image) a  sur boolder le nom du n°3bis de ce circuit.
https://www.boolder.com/en/fontainebleau/mont-ussy/12108-la-montee-des-pieds
renvoie vers https://bleau.info/c/4272.html alors qu'il faudrait renvoyer vers https://bleau.info/ussy/310586.html
Également, le n°3 jaune (https://www.boolder.com/en/fontainebleau/mont-ussy/12109-la-cuvette), nommé "les Deux Dalles" sur bleau.info (https://bleau.info/ussy/311618.html) est nommé sur boolder "la cuvette" et renvoie vers https://bleau.info/c/4274.html, le 12 ter du circuit orange.

Comme je suis tombé dessus immédiatement je n'ai pas vérifié pour toute la liste, mais je suppose que d'autres du circuit sont fausses également. Je n'ai pas remarqué d'erreur sur les autres circuits.

**Comment by nmondollot** [comment]
Merci beaucoup !
Nous avons corrigé les erreurs sur le site.
Cela apparaitra dans l'appli à la prochaine mise à jour.

PS: nous allons bientôt lancer un espace dédié pour remonter des erreurs / rajouter des voies manquantes
n'hésitez pas à y jeter un oeil : https://www.boolder.com/fr/contribute
