### ISSUE TITLE
Missing topo image?

### ISSUE THREAD

**Issue by pkamps** [boolder-org/boolder-data#6]
I believe the DB is referencing a topo image that does not exists:
https://github.com/boolder-org/boolder-data/tree/main/topos/area-10/topo-7094.jpg

**Comment by nmondollot** [comment]
Hello,

You are right.
The topo has changed and but we didn't add the file in the repo.

I'll see if we can automate this kind of thing.

In the mean time you can find the topo here: https://www.boolder.com/fr/fontainebleau/95-2/2894

**Comment by nmondollot** [comment]
Solved, check out the new documentation: https://github.com/boolder-org/boolder-data/tree/main?tab=readme-ov-file#topo
