### ISSUE TITLE
Missing topo images

### ISSUE THREAD

**Issue by mathiasbie** [boolder-org/boolder-data#7]
Hello, I noticed that some images are missing from your topo database. For example, the image for topo_id 12872 in area 20 doesn't exist.  
I can provide you a complete list if needed.  
Also, we regularly add new boulders in our database. Would you like us to work together on a process to add them to your database as well?

**Comment by nmondollot** [comment]
Hello Mathias,
You're right, some topos are missing.
Good news is that you can access them directly using this new url: `http://assets.boolder.com/proxy/topos/3846`
We'll stop adding them to the repo as it's not necessary anymore.

> Also, we regularly add new boulders in our database. Would you like us to work together on a process to add them to your database as well?
Yes! Can you send us an email at hello@boolder.com ? Thx

**Comment by nmondollot** [comment]
Updated doc: https://github.com/boolder-org/boolder-data/tree/main?tab=readme-ov-file#topo

**Comment by mathiasbie** [comment]
Désolé j'avais pas les notifications, je t'envoie un mail dans la journée.
